replicaCount: 2
image:
repository: slkgroup.jfrog.io/docker-local/maven1
  tag: latest
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
service:
  name: mavenwebappsvc
  type: LoadBalancer
  port: 80
  targetPort: 8080
