replicaCount: 2
 
image:
repository: slkgroup.jfrog.io/docker-local/maven-web-app/maven-web-app
  tag: 1
 
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
