replicaCount: 2

image:
  repository: adarsha.jfrog.io/sample/maven
  pullPolicy: IfNotPresent
  tag: 5

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  name: mavenwebappsvc
  type: LoadBalancer
  port: 80
  targetPort: 8080
