apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mavenwebapp.fullname" . }}
spec:
  revisionHistoryLimit: 10
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: {{ include "mavenwebapp.fullname" . }}
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebappcontainer
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
 
---
apiVersion: v1
kind: Service
metadata:
name: {{ .Values.service.name }}
spec:
  selector:
    app: mavenwebapp
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
